version: '3'

services: 
  nuxt:
    image: node:14.8.0-alpine3.12
    working_dir: /app
    volumes:
      - .:/app
    command: yarn dev
    environment:
      - NUXT_HOST=0.0.0.0
    ports: 
      - 3000:3000
    # root権限でファイルが作られるのを防ぐ
    user: '${UID}:${GID}'
